### ISSUE TITLE
Decide ui of shiny app

### ISSUE THREAD

**Issue by sdhutchins** [u-brite/SNVariome#4]
- [x] Use shiny's ui editor
- [x] Discuss with team what layouts would be appropriate
- [x] Look at existing shiny apps to generate ideas

**Comment by sdhutchins** [comment]
The editor is here https://rstudio.github.io/shinyuieditor/

**Comment by Poojas241** [comment]
Layouts
https://shiny.rstudio.com/articles/layout-guide.html#:~:text=Shiny%20includes%20a%20number%20of%20facilities%20for%20laying,layout%20system%20%28i.e.%2C%20fluidRow%20%28%29%20%26%20column%20%28%29%29.

**Comment by sdhutchins** [comment]
Addressed by PR #13
